Analpa 2614 bendparameters
finnishtransportagency/vaylariski-frontend pull request #36
Opened 2023-08-07 12:41 UTC by henriikkaha

Changed infotext, added autocomplete for gdogids, made icons for parameters, changed components to mui

2023-08-17 13:11 UTC, CeduDev commented
As can be seen in the image, the content in the button is not properly alligned to the center. This left side has more space to the than the right side (all three buttons). This is most likely due to the svg's have a viewbox of fixed size which is wider than the actual svg image. Not a critical thing but could be nice to fix if possible.
![image](https://github.com/finnishtransportagency/vaylariski-frontend/assets/75533906/2c4c17ed-cbb0-40c2-8789-fe97c0355fe6)

2023-08-17 13:12 UTC, CeduDev commented
> As can be seen in the image, the content in the button is not properly alligned to the center. This left side has more space to the than the right side (all three buttons). This is most likely due to the svg's have a viewbox of fixed size which is wider than the actual svg image. Not a critical thing but could be nice to fix if possible. ![image](https://user-images.githubusercontent.com/75533906/261318075-2c4c17ed-cbb0-40c2-8789-fe97c0355fe6.png)

Additionally, the buttons could be given a small margin as they look very cramped between the table and the tab

2023-08-17 13:15 UTC, CeduDev commented
I'd recommed setting a top and bottom margin around the blue button. The size could be the same as between the grey submit button and the white area beneath it.
![image](https://github.com/finnishtransportagency/vaylariski-frontend/assets/75533906/ca7e473f-07f5-4c2e-8648-312781afc23f)

2023-08-17 13:17 UTC, CeduDev requested changes
Looks good, love the images and svgs used! The given suggestions could be addressed/applied, otherwise it's good

2023-08-17 13:17 UTC, CeduDev commented on src/icons/BendRadiusIconSelected.js
> +      // style="background-color: rgb(255, 255, 255);"
```suggestion
```

2023-08-17 13:17 UTC, CeduDev commented on src/icons/BendRadiusIconSelected.js
> +      // style="background-color: rgb(255, 255, 255);"
Remove commented code

2023-08-17 13:27 UTC, CeduDev commented on src/icons/BendRadiusIconSelected.js
> +      // style="background-color: rgb(255, 255, 255);"
fixed

2023-08-17 13:48 UTC, CeduDev approved these changes

2023-08-18 10:33 UTC, adikele approved these changes

2023-08-18 10:52 UTC, merged